import type { Component } from "./types";

export const MOCK_COMPONENTS: Record<string, Component[]> = {
  base: [
    {
      component_id: "base_brown_rice",
      component_name: "Brown Rice",
      category: "base",
      is_available: true,
      default_portion: 200,
      unit: "g",
      calories: 220,
      protein: 5,
      carbs: 45,
      fat: 2,
      min_portion: 100,
      max_portion: 300,
      portion_step: 50,
      description: "Nutty, fiber-rich whole grain",
      fiber: 3.5,
      cost: 8000,
      skip_portion: false,
    },
    {
      component_id: "base_white_rice",
      component_name: "White Rice",
      category: "base",
      is_available: true,
      default_portion: 200,
      unit: "g",
      calories: 260,
      protein: 4.5,
      carbs: 56,
      fat: 0.5,
      min_portion: 100,
      max_portion: 300,
      portion_step: 50,
      description: "Classic steamed jasmine rice",
      fiber: 0.5,
      cost: 6000,
      skip_portion: false,
    },
    {
      component_id: "base_quinoa",
      component_name: "Quinoa",
      category: "base",
      is_available: true,
      default_portion: 200,
      unit: "g",
      calories: 240,
      protein: 8,
      carbs: 39,
      fat: 4,
      min_portion: 100,
      max_portion: 300,
      portion_step: 50,
      description: "Protein-rich ancient grain",
      fiber: 5,
      cost: 12000,
      skip_portion: false,
    },
    {
      component_id: "base_cauliflower",
      component_name: "Cauliflower Rice",
      category: "base",
      is_available: true,
      default_portion: 200,
      unit: "g",
      calories: 50,
      protein: 4,
      carbs: 10,
      fat: 0.5,
      min_portion: 100,
      max_portion: 300,
      portion_step: 50,
      description: "Low-carb rice alternative",
      fiber: 4,
      cost: 10000,
      skip_portion: false,
    },
  ],

  protein: [
    {
      component_id: "protein_chicken",
      component_name: "Grilled Chicken",
      category: "protein",
      is_available: true,
      default_portion: 150,
      unit: "g",
      calories: 248,
      protein: 46,
      carbs: 0,
      fat: 5,
      min_portion: 100,
      max_portion: 250,
      portion_step: 50,
      description: "Lean herb-marinated chicken breast",
      fiber: 0,
      cost: 25000,
      skip_portion: false,
    },
    {
      component_id: "protein_tofu",
      component_name: "Pan-seared Tofu",
      category: "protein",
      is_available: true,
      default_portion: 150,
      unit: "g",
      calories: 180,
      protein: 18,
      carbs: 4,
      fat: 11,
      min_portion: 100,
      max_portion: 250,
      portion_step: 50,
      description: "Crispy organic tofu blocks",
      fiber: 1.5,
      cost: 15000,
      skip_portion: false,
    },
    {
      component_id: "protein_salmon",
      component_name: "Salmon Fillet",
      category: "protein",
      is_available: true,
      default_portion: 120,
      unit: "g",
      calories: 250,
      protein: 30,
      carbs: 0,
      fat: 14,
      min_portion: 80,
      max_portion: 200,
      portion_step: 40,
      description: "Wild-caught Atlantic salmon",
      fiber: 0,
      cost: 45000,
      skip_portion: false,
    },
    {
      component_id: "protein_beef",
      component_name: "Beef Strips",
      category: "protein",
      is_available: true,
      default_portion: 120,
      unit: "g",
      calories: 300,
      protein: 34,
      carbs: 0,
      fat: 18,
      min_portion: 80,
      max_portion: 200,
      portion_step: 40,
      description: "Grass-fed sirloin strips",
      fiber: 0,
      cost: 35000,
      skip_portion: false,
    },
  ],

  cook_veg: [
    {
      component_id: "veg_broccoli",
      component_name: "Broccoli",
      category: "cook_veg",
      is_available: true,
      default_portion: 100,
      unit: "g",
      calories: 35,
      protein: 3,
      carbs: 7,
      fat: 0.4,
      min_portion: 50,
      max_portion: 200,
      portion_step: 50,
      description: "Steamed fresh broccoli florets",
      fiber: 2.6,
      cost: 8000,
      skip_portion: false,
    },
    {
      component_id: "veg_spinach",
      component_name: "Sautéed Spinach",
      category: "cook_veg",
      is_available: true,
      default_portion: 100,
      unit: "g",
      calories: 23,
      protein: 3,
      carbs: 4,
      fat: 0.3,
      min_portion: 50,
      max_portion: 200,
      portion_step: 50,
      description: "Garlic-sautéed baby spinach",
      fiber: 2.2,
      cost: 7000,
      skip_portion: false,
    },
    {
      component_id: "veg_zucchini",
      component_name: "Zucchini",
      category: "cook_veg",
      is_available: true,
      default_portion: 100,
      unit: "g",
      calories: 17,
      protein: 1.2,
      carbs: 3,
      fat: 0.3,
      min_portion: 50,
      max_portion: 200,
      portion_step: 50,
      description: "Grilled zucchini slices",
      fiber: 1,
      cost: 6000,
      skip_portion: false,
    },
  ],

  sauce: [
    {
      component_id: "sauce_teriyaki",
      component_name: "Teriyaki",
      category: "sauce",
      is_available: true,
      default_portion: 30,
      unit: "ml",
      calories: 45,
      protein: 2,
      carbs: 10,
      fat: 0,
      min_portion: 0,
      max_portion: 0,
      portion_step: 0,
      description: "Sweet soy glaze",
      fiber: 0,
      cost: 0,
      skip_portion: true,
    },
    {
      component_id: "sauce_peanut",
      component_name: "Peanut Sauce",
      category: "sauce",
      is_available: true,
      default_portion: 30,
      unit: "ml",
      calories: 90,
      protein: 4,
      carbs: 6,
      fat: 7,
      min_portion: 0,
      max_portion: 0,
      portion_step: 0,
      description: "Creamy Thai-style peanut",
      fiber: 0,
      cost: 0,
      skip_portion: true,
    },
    {
      component_id: "sauce_soy_ginger",
      component_name: "Soy Ginger",
      category: "sauce",
      is_available: true,
      default_portion: 30,
      unit: "ml",
      calories: 25,
      protein: 1.5,
      carbs: 5,
      fat: 0,
      min_portion: 0,
      max_portion: 0,
      portion_step: 0,
      description: "Light soy with fresh ginger",
      fiber: 0,
      cost: 0,
      skip_portion: true,
    },
  ],

  raw_veg: [
    {
      component_id: "raw_avocado",
      component_name: "Avocado",
      category: "raw_veg",
      is_available: true,
      default_portion: 50,
      unit: "g",
      calories: 80,
      protein: 1,
      carbs: 4,
      fat: 7,
      min_portion: 30,
      max_portion: 100,
      portion_step: 10,
      description: "Creamy ripe avocado slices",
      fiber: 3.4,
      cost: 10000,
      skip_portion: false,
    },
    {
      component_id: "raw_cucumber",
      component_name: "Cucumber",
      category: "raw_veg",
      is_available: true,
      default_portion: 50,
      unit: "g",
      calories: 8,
      protein: 0.3,
      carbs: 2,
      fat: 0.1,
      min_portion: 30,
      max_portion: 100,
      portion_step: 10,
      description: "Crisp fresh cucumber",
      fiber: 0.5,
      cost: 3000,
      skip_portion: false,
    },
  ],

  topping: [
    {
      component_id: "topping_sesame",
      component_name: "Sesame Seeds",
      category: "topping",
      is_available: true,
      default_portion: 10,
      unit: "g",
      calories: 57,
      protein: 2,
      carbs: 2,
      fat: 5,
      min_portion: 0,
      max_portion: 0,
      portion_step: 0,
      description: "Toasted white & black sesame",
      fiber: 1,
      cost: 0,
      skip_portion: true,
    },
    {
      component_id: "topping_almonds",
      component_name: "Almonds",
      category: "topping",
      is_available: true,
      default_portion: 15,
      unit: "g",
      calories: 87,
      protein: 3,
      carbs: 3,
      fat: 7,
      min_portion: 0,
      max_portion: 0,
      portion_step: 0,
      description: "Crunchy roasted almonds",
      fiber: 1.5,
      cost: 0,
      skip_portion: true,
    },
  ],

  egg: [
    {
      component_id: "egg_soft_boiled",
      component_name: "Soft-boiled Egg",
      category: "egg",
      is_available: true,
      default_portion: 1,
      unit: "count",
      calories: 70,
      protein: 6,
      carbs: 0.5,
      fat: 5,
      min_portion: 1,
      max_portion: 3,
      portion_step: 1,
      description: "Jammy 6-minute egg",
      fiber: 0,
      cost: 5000,
      skip_portion: false,
    },
    {
      component_id: "egg_poached",
      component_name: "Poached Egg",
      category: "egg",
      is_available: true,
      default_portion: 1,
      unit: "count",
      calories: 70,
      protein: 6,
      carbs: 0.5,
      fat: 5,
      min_portion: 1,
      max_portion: 3,
      portion_step: 1,
      description: "Classic runny poached egg",
      fiber: 0,
      cost: 5000,
      skip_portion: false,
    },
  ],

  cooking_oil: [
    {
      component_id: "oil_olive",
      component_name: "Extra Virgin Olive Oil",
      category: "cooking_oil",
      is_available: true,
      default_portion: 10,
      unit: "ml",
      calories: 88,
      protein: 0,
      carbs: 0,
      fat: 10,
      min_portion: 0,
      max_portion: 0,
      portion_step: 0,
      description: "Cold-pressed Italian olive oil",
      fiber: 0,
      cost: 0,
      skip_portion: true,
    },
  ],
};
